name: Ruby Tests

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # - name: Run RuboCop
        # run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec 