name: Ruby Tests

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # - name: Run RuboCop
        # run: bundle exec rubocop

      - name: Run RSpec with coverage
        run: bundle exec rspec
        env:
          COVERAGE: true
          MIN_COVERAGE: 90

      - name: Check coverage threshold
        run: |
          COVERAGE=$(cat coverage/.last_run.json | jq '.result.line')
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90% (Current: $COVERAGE%)"
            exit 1
          fi 